name: basketball_ptr
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  shared:
    path: ../_shared

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: FjallaOne
      fonts:
        - asset: fonts/FjallaOne-Regular.ttf

  uses-material-design: true
