name: parallax_travel_cards_list
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../_shared/

  cupertino_icons: ^0.1.2


flutter:

  uses-material-design: true

  assets:
   - images/London/
   - images/Pisa/
   - images/Budapest/
   - images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/Open-Sans/OpenSans-Regular.ttf
        - asset: fonts/Open-Sans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open-Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open-Sans/OpenSans-Semibold.ttf
          weight: 600
        - asset: fonts/Open-Sans/OpenSans-ExtraBold.ttf
          weight: 800
    - family: DMSerifDisplay
      fonts:
        - asset: fonts/DM-Serif-Display/DMSerifDisplay-Regular.ttf
        - asset: fonts/DM-Serif-Display/DMSerifDisplay-Italic.ttf
          style: italic
